// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionFavorites
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionFavorites.9f81ec6e-5c91-4809-9dde-9b3166c327fd";
        public const string Name = "Solution Favorites";
        public const string Description = @"Pin your frequently used files to a Favorites node in Solution Explorer—including files from anywhere on disk, not just your solution.";
        public const string Language = "en-US";
        public const string Version = "1.0.902";
        public const string Author = "Mads Kristensen";
        public const string Tags = "favorites, pin, solution explorer, productivity";
        public const bool IsPreview = false;
    }
}
